[package]
name = "server"
version = "0.1.0"
authors = ["oselgithub <oselgithub@seznam.cz>"]

[dependencies]
hyper = "*"
iron = "*"
router = "*"
rustc-serialize = "*"

[dependencies.library-model]
path = "../library-model"
version  = "*"
